# Generated by Django 3.2.8 on 2021-12-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211122_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default='litreview_defaultimage.png', upload_to='images/'),
        ),
    ]
